#import "@preview/modern-cug-report:0.1.3": *
#show: doc => template(doc, size: 11.5pt,
  footer: "2026", header: "FieldMeta.jl Implementation Notes")

#set par(leading: 1em, spacing: 1em)

#align(center)[
  #text(20pt, weight: "bold")[FieldMeta.jl Implementation Notes]
]

#v(1em)

= 1 What Does Macro Expansion Generate?

The fastest way to understand this package is to look at what it ultimately produces.

```julia
@metadata bounds nothing Any
@metadata units  "-"    String

@bounds @units struct Muskingum
    x::Float64 | (0.01, 0.5) | "m/s"
    dt::Float64
end
```

Is equivalent to:

```julia
struct Muskingum          # pipe stripped clean
    x::Float64
    dt::Float64
end

# Each (type, field, key) → specialized method returning a constant
@inline _meta(::Type{<:Muskingum}, ::Val{:x}, ::Val{:bounds}) = (0.01, 0.5)
@inline _meta(::Type{<:Muskingum}, ::Val{:x}, ::Val{:units})  = "m/s"

# Per-key default fallback generated by @metadata
@inline _meta(::Type, ::Val, ::Val{:bounds}) = nothing
@inline _meta(::Type, ::Val, ::Val{:units})  = "-"
```

When the user calls `bounds(model, :x)`, internally it dispatches to
`_meta(Muskingum, Val{:x}(), Val{:bounds}())`.
Three-level priority: *specialized method > per-key default > MethodError (undeclared key)*.
The hot path is pure method dispatch — no Dict lookups, fully type-stable.

= 2 Pipe Chain and Stackable Macros

`|` is a left-associative operator in Julia:

```
x::T | v1 | v2 | v3   ≡   ((x::T | v1) | v2) | v3
```

The leftmost value `v1` lives in the deepest `:|` node.
Julia expands macros from outer to inner, so:

- `@bounds` (outermost) strips `v1`, passes `x::T | v2 | v3` to the next macro.
- `@units` strips `v2`, passes `x::T | v3`.
- `@description` strips `v3`, leaving the clean `x::T`.

The core implementation is `_strip_leftmost!(args, i)` (7 lines), which
recursively locates the deepest `:|` node, replaces it in-place, and returns
the stripped value.

= 3 When Does Type Checking Happen?

#table(columns: (auto, 1fr),
  align: (left, left),
  stroke: 0.5pt + gray,
  table.header[Phase][Action],
  [Macro expansion],    [Read constraint `c` from `REGISTRY`; error immediately if key undeclared],
  [Struct definition],  [`let v = $val; v isa c || _typeerror(...)` runs once],
  [Access (hot path)],  [Specialized method returns `$val` directly — *zero overhead*],
)

`REGISTRY` is written only when `@metadata` runs and read only during macro
expansion; it is never touched at runtime.

= 4 Internal Function Call Chain

When `@bounds struct ... end` expands, the call structure is:

```julia
macro bounds(ex)
  _stack(ex, :bounds, src)
    _process(ex, src, emit_fn)
      1. _find_struct(ex)              # locate :struct, pierce @with_kw macrocalls
      2. for each field line:
           a. _meta_slot(block, i)     # has pipe? -> (args, idx, fname)
           b. _strip_leftmost!(args, idx)  # strip leftmost | value in-place, return val
           c. _emit!(methods, T, fname, key, val)
                - REGISTRY[key]        # read constraint c (macro-expansion time, once)
                - push! generated block:
                    let v=val; v isa c || _typeerror(...) end  # runs at definition time
                    @inline _meta(::Type{<:T}, ::Val{f}, ::Val{k}) = val
      3. return Expr(:block, esc(ex), methods...)
```

Step 2 is three sequential sub-steps (a → b → c), not nested calls.
`ex` is mutated in-place during step 2 (pipe stripped); by step 3 it is already
a clean struct expression.

== Expansion Order with Multiple Stacked Macros

Stacking does not rely on a loop in the code — it is driven by Julia's own
macro expansion mechanism. Expansion (compile time) and execution (runtime)
are two distinct phases:

*Expansion phase* (outer → inner, compile time):
```julia
@bounds @units struct ... x | v1 | v2 end
  @bounds expands -> block { esc(@units struct...x|v2 end),   # ex first
                              @inline _meta(...bounds...) = v1 }
  @units  expands -> block { esc(struct...x end),              # ex first
                              @inline _meta(...units...) = v2 }
```

*Execution phase* (sequential, runtime):
```
1. struct ... x end                        <- struct defined first
2. @inline _meta(...units...)  = v2        <- method references T, T already exists ✓
3. @inline _meta(...bounds...) = v1
```

`_process` always places `esc(ex)` before `methods` in the returned block,
guaranteeing the struct is defined before any `_meta` method that references it.


= 5 Debug Entry Points

```julia
import FieldMeta: _ispipe, _find_struct, _fieldname, _strip_leftmost!, _meta_slot

# Feed quoted expressions directly to internal helpers
holder = Any[:(x::Int | (0, 1) | "m")]
_strip_leftmost!(holder, 1)   # => :((0, 1))

# Inspect the full expansion
@macroexpand @bounds @units struct Foo; x::Int | 1 | "u"; end
```

Every helper's behaviour is covered by runnable examples in `test/test-internals.jl`.
